### PR TITLE
[About]Page style modified

### PR DESCRIPTION
**Pull request by fgonzalezr1998**
* Animation of members images modified.

* Background changed (grey).

This PR solves issue #83

### CODE REVIEW

**Comment by jginesclavero** [comment]
@fgonzalezr1998 Attach an image please. Thank you!

**Comment by fgonzalezr1998** [comment]
Oh Sorry!

## Screenshots:

Screenshot from 2020-09-21 17-45-18

Screenshot from 2020-09-21 17-45-25

**Comment by jginesclavero** [comment]
Could you up a bit the job titles?

**Comment by fgonzalezr1998** [comment]
## Screenshot:

Screenshot from 2020-09-22 11-34-17

**Comment by jginesclavero** [comment]
Looks very nice! Thank you @fgonzalezr1998

**Pull request merged**
